### ISSUE TITLE
Please add support for VS2019

### ISSUE THREAD

**Issue by BritBlaster** [justcla/HotSettings#13]
I tried the instructions at https://madskristensen.net/blog/how-to-upgrade-extensions-to-support-visual-studio-2019/
But this did not work -- install failed with:
Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing
Microsoft.VisualStudio.Component.CoreEditor

**Comment by justcla** [comment]
Looking in to it.

**Comment by justcla** [comment]
This extension is now fully compliant with VS2019.
