### ISSUE TITLE
Provide toolbar with hot buttons

### ISSUE THREAD

**Issue by justcla** [justcla/HotSettings#5]
User request from Daniel Chay for the Hot Settings toolbar:

> The toolbar is what I wanted back. I turned off all the buttons I did not want to see and left the buttons I wanted quick access to toggle editor features.
> The most common buttons I use are: Line Numbers and BreakPoint margin (off when coding, on when debugging). Sometimes I turn on the Navigation Bar for awhile then turn it back off. There are a couple of others I use less regularly.
> I really like the new Full Screen button!

**Comment by justcla** [comment]
Popular buttons:
- Line Numbers
- BreakPoint margin
- Navigation Bar
- Full Screen

**Comment by justcla** [comment]
Toolbar restored with lots of options available. (Some deliberately excluded)
See release 1.1.5

**Comment by ghost** [comment]
Looks Great!

**Comment by ZAIDI123** [comment]
Line Numbers
BreakPoint margin
Navigation Bar
Full Screen

**Comment by ZAIDI123** [comment]
Line Numbers
BreakPoint margin
Navigation Bar
Full Screen

**Comment by ZAIDI123** [comment]
Line Numbers
BreakPoint margin
Navigation Bar
Full Screen

**Comment by ZAIDI123** [comment]
Line Numbers
BreakPoint margin
Navigation Bar
Full Screen
